python AttentionRetrieval.py \
--dataset=pittsburgh \
--mode=train \
--savePath=ckpt_vgg16_pitts30_a \
--arch=vgg16 \
--numTrain=5 \
--weightDecay=0.01 \
--cacheBatchSize=64 \
--batchSize=4 \
--withAttention \
--vladv2 \
--threads=4
